---
title: "ref"
format: 
  docx:
    toc: true
  html:
    css: colors.css
editor: visual
bibliography: references.bib
execute:
  # show code chunk output
  include: true
  # Show the code in the output
  echo: false
  # Show messages
  message: false
  # Show warnings
  warning: false
  # Cache code results
  cache: true
---

# Argument bib

## Introduction

- [@deichmann2018], Militate for increased passive acoustic monitoring in tropical ecosystems

-  The ‘soundscape’ incorpore all sounds emanating from any given habitat.
  it can be classified according to the source of the acoustic signal: geophony (climate and geography), biophony (all living organisms), and anthrophony (human activities) [@pijanowski2011].
  The latter incorporates technophony (machinary noises) [@fuller2015]

- Advance in Soudscape ecology, enabled some better understanding of the structure and dynamics of the sonic environment [@pijanowski2011] a,b?.

- The Soundscape approach consider all components and analysed the sonic patterns emerging from the relations of sound sources and habitat topologies [@fuller2015] and temporal dynamics (Gage and Axel, 2014) [@farina2016]

- Acoustic indices are used for quantitative soundscape analyses to monitor ecosystem condition via a numeric summary of the soundscape.
  Ecological meaning is inferred by relating acoustic indices to diversity metrics (Gasc et al., 2013;[@dröge2021]Eldridge et al., 2018; or to habitat quality([@fuller2015] [@sánchez-giraldo2021]) [@rudge2026]

- Acoustic indices uses in combinations to characterise soundscape and distinguish among habitat conditions or diversity metrics [@sánchez-giraldo2021]

- The acoustic signature of each species can be used to measure the acoustic niche overlap and breadth of the entire community (e.g. Sinsch et al., 2012).
  At every hourly interval different species interact acoustically, confirming the dynamic character of an acoustic community.
  [@farina2016]

[@malavasi2012] From empirical observations it is known that species can limit acoustic overlap in both frequency and time (Malavasi and Farina, 2013).
This frequency/time partitioning is conceptualized by the acoustic niche hypothesis (ANH).

- Invasive species monitoring via pam are scarce (invasive amerianc bullfrog[@bota2024]; invasive fish [@rountree2017]; invasive bird [@wood2020])

- Alien Invasive species monitoring via pam [@ribeiro2022]

- PAM for rapid surveys of biodiversity, acoustic indices can be rapidly extracted from hundreds of hours of recordings [@sueur2008]

- Soundscape can provide indicators on the ecological processes or disturbances (cite plein d'artcile dont [@villanueva-rivera2011] [@deichmann2018]. Nevertheless, acoustic indices struggle to have generalasible results across taxa and ecosystems [@buxton2018]

What implications for Acoustic Niche hypothesis

[@ross2023] pour avoir les review déjà faites en pam...

- Soundscape can provide indicators on the ecological processes or disturbances (cite plein d'artcile dont [@villanueva-rivera2011] [@deichmann2018], informe sur les reviews de dispo sur les PAM (la classique).
  Avantage des PAM car peut faire du multitaxon, multi-espèce, can do scaling up spatially and oenvironmental sound producing.

<!-- -->

- PAM is increasingly used to map biodiversity in remote or challenging habitats such as tropical forest [@burivalova2019]

<!-- -->

- PAM can also en able data acquisition during seasons of heightened inaccessibility, such as during floods or rainy seasons, which often coincide with important life-history stages for vocalising birds and mammals [@szymanski2021]

- PAM requires minimal manual parameter tuning and non invasive wildlife studies, monitor variety of cryptic and elusive species [@wrege2017] [@yusni2026]

[@ross2023] PAM permits to study the disturbance with the same equipment as affected organisms.
Methodological spatial scale-up, multi-taxa...
Challenge with signal strengh and species dectability and frequencies of calls.
Target Soundscape are afffected by non-target sound, within geophony or anthropophony.

Beyond geographical remoteness,

- In New Caledonian forests, the invasive ant Wasmannia auropunctata caused a reduction of local insect biodiversity, lead ing to impoverishment of the soundscape (\~80% cricket call decline) [@gasc2018]

- [@scarpelli2020] Tropical ecosystems remains largely understudied, the relation between acoustic rich, complex composition [@donascimento2020] and landscape integrity are lacking.

Insular ecosystems offer the opportunity to studied this relationship within a less complex framework ( ) and

In this study we investigate the relationship between soundscape variation and the acoustic avian community and habitats

- Birds introduced are issued from specific families (e.g., Galliniformes,Columbidae, Fringillidae, Passeridae, Estrildidae and Sturnidae ..) introduced for hunting, aesthetic purposes with accidental or intentional releases of cage [@blackburn2001][@dyer2017]

- This species shows peculiar traits such as granivoes and are adapted to urban and agricultural landscapes, whereas native birds from oceanic island tends to include frugivore and insectivore species occuring in forests [@soares2021]

In Tahiti a single man introduced lot of species ""

Limited studies on insular tropical terrestrial soundscape

The acoustic habitat: The sonic context in which species are living

- Sonotope or acoustic habitats (he sonic context in which species are living) , as recently argued by Merchant et al. (2015), are the result of natural and man-made processes, and differ according to the location, creating specific acoustic identities [@farina2016].

- A sonotope is an important ingredient in the habitat quality of acoustic communities and its assessment represents a good proxy for predicting and explaining the distribution of species in space and time.
  [@farina2016]

- This signature can be considered equivalent to a biological code (Barbieri, 2015) and is species- and communityspecific (Farina and Pieretti, 2014a; Malavasi et al., 2014).

Moreover, the three components of a sonotope may be present, each with a different importance, inside a single sonotope.
For instance, in urban landscapes, technophonies (often also called anthrophonies) will likely contribute more than 90% of the sound energy (Joo et al., 2011),

- The soundtope (Soundscape level) model is equivalent to the acoustic community concept but the soundtope model incorporates environmental conditions not considered by the acoustic community model used to describe only biophonic processes (Que la biophony) (Fig. 5).
  In fact, the composition of an acoustic community is a good proxy for a broad appraisal of the biodiversity at a location.
  [@farina2016]

- Today it is possible to describe the acoustic composition of an acoustic community on a large scale [@towsey2014]

- Our study stands at the ecoacoustic level, but aims to focus the spatial variation of the birds acoustic community in Tahiti, diverging in space by the native or introduced origin of it's species.

\## M & M

## Résultat

Our results from automatic detection showed a higher native species richness in forest sites (... species) than introduced in urbna areas (... species).

## Discussion

*1erparagraphe*

Rappel de l'enejux Our study shows relevant findings to the understanding of the relationship between soundscape ...
Quel realtion du du soundscape et de l'habitat Et quel relation avec l'envionnement changeant de bird species

*2emeparagraphe*

Quel overall pattern entre les différences indices/focus sur l'indice qui fonctionne le mieux

*paragrapheanalysis*

In tropical landscapes, patterns in acoustic indices may depend on the sampling scheme, as a more number of recordings or longer sampling time tend to decrease the indices variation [@bradfer-lawrence2019]

*paragrapheccl*

Soundscape is very important for places for human relevantness to a place and for xhat bird species hear in their communication.
Here, we aim to adress a discarded issue with introduced species having imapct on the ..
of a place and on natve bird species

Homogenisation of the soundscape has a lost of resilience , acoustic heritage and interferenc in communication in birds

Introduced species are numerous, surpassing original native diversity plus typical vocally active species, due to their family origin or origin of trade (bird song in cage trade)

Therefore, species whose acoustic signals are similar to competitors' one may either become excluded from successfully signalling at a particular time or frequency, or may employ vocal compensation to partition their acoustic space to minimize competition [@tennessen2016]

FInd an article on the acoustic complecity of some bird families, that soud match with the most introduced ones.
