---
title: "variable"
format: 
  docx:
    toc: true
  html:
    css: colors.css
editor: visual
bibliography: references.bib
---

```{r}
data <- readxl::read_excel("data/Data_Globale_Tahiti.xlsx")
```
```{r}
theme_soundscape <- function() {
  
  theme_minimal() +
    
  theme(
    panel.background = element_rect(fill = "#F8FAFC", colour = NA),
    plot.background  = element_rect(fill = "#F8FAFC", colour = NA),

    panel.grid.major.y = element_line(color = "#CBD5E1", linewidth = 0.4),
    panel.grid.major.x = element_blank(),
    panel.grid.minor = element_blank(),

    axis.text  = element_text(color = "#64748B", size = 11),
    axis.title = element_text(color = "#64748B", size = 12, face = "bold"),

    axis.line = element_line(color = "#64748B", linewidth = 0.5),
    axis.ticks = element_line(color = "#64748B"),

    legend.background = element_rect(fill = "#F8FAFC"),
    legend.text = element_text(color = "#64748B"),
    legend.title = element_text(color = "#64748B", face = "bold")
  )
}
```


```{r}
library(tidyverse)
library(ggplot2)
# Graphique HSA
graph_hsa <- ggplot(data, aes(x = site, y = HSA, fill = HSA)) +
  geom_col(width = 0.8, na.rm = TRUE) +
  scale_fill_gradient(
    low = "#DCEAF7",
    high = "#1769AA",
    name = "HSA"
  ) +
  labs(
    x = "Site",
    y = "Hard Surface Area (%)",
  ) +
  theme_soundscape() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1)
  )
# Graphique HERB
graph_herb <- ggplot(data, aes(x = site, y = HERB, fill = HERB)) +
  geom_col(width = 0.8, na.rm = TRUE) +
  scale_fill_gradient(
    low = "#E8F5E9",
    high = "#2E7D32",
    name = "HERB"
  ) +
  labs(
    x = "Site",
    y = "Herbaceous vegetation (%)",
  ) +
  theme_soundscape() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1)
  )


# Afficher les deux graphiques
graph_hsa
graph_herb
```
```{r}
cor(data$HSA,data$HERB)
```
```{r}
library(sf)
library(leaflet)
library(ggspatial)
library(viridis)
```

```{r}
sites_sf <- data %>%
  mutate(
    latitude = as.numeric(Latitude),
    longitude = as.numeric(Longitude)
  ) %>%
  sf::st_as_sf(
    coords = c("longitude", "latitude"),
    crs = 4326
  )
```


```{r}
#ggplot() +
  annotation_map_tile(
    type = "osm",
    zoom = 12
  ) +
  geom_sf(
    data = sites_sf,
    aes(color = Alt),
    size = 4,
    alpha = 0.9
  ) +
  geom_sf_text(
    data = sites_sf,
    aes(label = site),
    size = 3,
    nudge_y = 0.002
  ) +
  scale_color_viridis_c(
    option = "C",
    name = "Altitude (m)"
  ) +
  annotation_scale(location = "bl") +
  annotation_north_arrow(
    location = "tr",
    style = north_arrow_fancy_orienteering()
  ) +
  labs(
    x = "Longitude",
    y = "Latitude"
  ) +
  theme_minimal()
```
```{r}
#ggsave(
#  "carte_sites_tahiti.png",
#  width = 10,
#  height = 8,
#  dpi = 300)
```

